- hosts: "alpaca-cluster"
  become: true
  become_user: root

  tasks:
    - name: Install Dependencies
      ansible.builtin.apt:
        name: curl
        state: present
        update_cache: true

    - name: Download k3s
      ansible.builtin.get_url:
        url: https://github.com/k3s-io/k3s/releases/download/v1.26.5+k3s1/k3s
        dest: /usr/local/bin/k3s
        mode: '111'