---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bazarr
    use: media-infra
  name: bazarr
  namespace: default
spec:
  selector:
    app: bazarr
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: bazarr
    use: media-infra
  name: bazarr
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bazarr
  serviceName: bazarr
  template:
    metadata:
      labels:
        app: bazarr
        use: media-infra
    spec:
      containers:
      - image: linuxserver/bazarr:1.3.1
        name: bazarr
        ports:
        - containerPort: 6767
        resources:
          requests:
            cpu: "250m"
            memory: "250M"
          limits:
            cpu: "4000m"
            memory: "4G"
        volumeMounts:
        - name: data
          mountPath: /config
        securityContext:
          allowPrivilegeEscalation: true # not a best practice. linuxserver.io requirement
          readOnlyRootFilesystem: false # not a best practice
          runAsNonRoot: false         # not a best practice. linuxserver.io containers require root privilege
#          capabilities:
#            drop: 
#            - all
#          runAsUser: 103060          # linuxserver.io containers require root privilege
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: freenas-nfs-csi
      resources:
        requests:
          storage: 16Gi